#sprint1
AleksandraZakharova/BeautyLandingPage pull request #1
Opened 2021-10-18 03:32 UTC by AleksandraZakharova

Не хватило времени, чтобы закончить, вчера вечером начала, не успела:(

2021-10-19 10:20 UTC, studenttsu requested changes
Привет! Спасибо за внимательность к деталям в реализации - самая похожая на макет работа)

Есть моменты по коду и стоит реализовать пару элементов

2021-10-19 10:20 UTC, studenttsu commented on index.html
> +        <link rel="stylesheet" href="./main.css">
`нужно поправить`

На занятии не сказал, но стили нужно подключать ниже всех остальных подключаемых стилей. Ведь мы можем захотеть переопределить "внешние" стили

2021-10-19 10:20 UTC, studenttsu commented on index.html
> +        <link href="https://fonts.googleapis.com/css2?family=Montserrat:wght@700&display=swap" rel="stylesheet">
`можно лучше`

Хорошо бы объединить загрузку шрифтов один запросом.

`<link href="https://fonts.googleapis.com/css2?family=Montserrat:wght@400;500;600;700&display=swap" rel="stylesheet">`

2021-10-19 10:20 UTC, studenttsu commented on index.html
> +                        <span class="time-table">с 10.00 до 19.00 без выходных</span>
Интересное решение вынести отдельной строкой время работы, но правильней было бы объединить номер телефона и время работы в один блок и позиционировать именно его как необходимо по макету

![image](https://user-images.githubusercontent.com/12005449/137886819-6c1c85d9-7d83-42e6-b415-6df9205479cd.png)

2021-10-19 10:20 UTC, studenttsu commented on index.html
> +                                <div class="circle"></div>
`можно лучше`

Чтобы не делать доп. разметку, можно круг реализовать псевдоэлементом

2021-10-19 10:20 UTC, studenttsu commented on index.html
> +                                <div>
Не совсем понял зачем дополнительный внутренний div? И стоит помнить, что в секции Контакты тоже есть соц. сети и нужно подумать как можно реализовать, чтобы была возможность переиспользовать этот блок

2021-10-19 10:20 UTC, studenttsu commented on index.html
> +                                    <img src="./image/vk.svg">
`нужно поправить`

Иконки соц. сетей нужно сделать ссылкой и добавить атрибут `target="_blank"`

2021-10-19 10:20 UTC, studenttsu commented on index.html
> +                        <div class="about section">
`можно лучше`

Предпочтительней секции реализовывать именно тегом `section` - проще потом код читается

2021-10-19 10:20 UTC, studenttsu commented on index.html
> +                <footer class="footer">Footer</div>
Нужно реализовать содержимое футера

2021-10-19 10:20 UTC, studenttsu commented on index.html
> +                            </div>
В секцию О салоне также входит и 3 элемента, нужно реализовать в работе этого спринта
![image](https://user-images.githubusercontent.com/12005449/137888412-ccf8c38c-4a7a-4b15-8228-366c43d7d574.png)

2021-10-19 10:20 UTC, studenttsu commented on index.html
> +                <footer class="footer">Footer</div>
Нужно не забыть прижать футер к низу страницы

2021-10-19 10:20 UTC, studenttsu commented on main.css
> +html,
Правильно в самом начале указать браузеру как ему считать размеры блоков

```css
html {
    box-sizing: border-box;
}

*, *:before, *:after {
    box-sizing: inherit;
}
```

2021-10-19 10:20 UTC, studenttsu commented on main.css
> +    font-family: 'Montserrat', sans-serif;
`нужно поправить`

Не стоит каждый раз указывать шрифт, достаточно один раз указать в body, дочерние элементы унаследуют это стили. Кастомизировать останется лишь размер шрифта и толщину начертания

Нужно далее выпилить указание шрифта, кроме кнопки.

2021-10-19 10:20 UTC, studenttsu commented on main.css
> +    padding: 0;
`нужно поправить`

У заголовков по дефолту `padding: 0`, поэтому не стоит дополнительно обнулять внутренний отступ.
Чтобы понимать какие дефолтные стили определены браузером, можно пользоваться devtools
![image](https://user-images.githubusercontent.com/12005449/137889835-bb292bb0-4052-4048-9383-b44eefbd63f7.png)

2021-10-19 10:20 UTC, studenttsu commented on main.css
> +    font-style: normal;
`нужно поправить`

По дефолту у всего текста `font-style: normal`, поэтому не стоит дополнительно указывать

2021-10-19 10:20 UTC, studenttsu commented on main.css
> +    margin: 0;
`нужно поправить`

`span` - строчный элемент, поэтому внешний отступ проигнорируется браузером. Да и смысла нет задавать нулевой внешний отступ

2021-10-19 10:20 UTC, studenttsu commented on main.css
> +a {
`можно лучше`

Хорошая практика глобальные стили указывать вверху файла стилей

2021-10-19 10:20 UTC, studenttsu commented on main.css
> +    cursor: url(./image/pointer.svg) 14.47 15.25, pointer;
`нужно поправить`

это лишнее, достаточно `cursor: pointer`

2021-10-19 10:20 UTC, studenttsu commented on main.css
> +h1{
Стоит придерживаться единого стиля форматирования. Где-то есть пробел между фигурными скобками, где-то нет

2021-10-19 10:20 UTC, studenttsu commented on main.css
> +
Не стоит оставлять и пустые строки в коде

2021-10-19 10:20 UTC, studenttsu commented on main.css
> +    right: calc((100% - 1110px) / 2);
Интересное решение, но это лишнее. Достаточно спозиционировать абсолютно относительно контейнера шапки (.container)

2021-10-19 16:34 UTC, AleksandraZakharova commented on main.css
> +    font-family: 'Montserrat', sans-serif;
Привет, спасибо большое за рекомендации! Остался вопрос: а почему в кнопке не надо убирать font-family?

2021-10-20 08:50 UTC, studenttsu commented on main.css
> +    font-family: 'Montserrat', sans-serif;
Элементы формы не наследуют шрифт от родителя, самое простое кнопке указать

```
button {
  font-family: inherit;
}
```

2021-10-24 13:10 UTC, AleksandraZakharova commented on index.html
> +        <link rel="stylesheet" href="./main.css">
fixed

2021-10-24 13:10 UTC, AleksandraZakharova commented on index.html
> +        <link href="https://fonts.googleapis.com/css2?family=Montserrat:wght@700&display=swap" rel="stylesheet">
fixed

2021-10-24 13:10 UTC, AleksandraZakharova commented on main.css
> +a {
fixed

2021-10-24 13:11 UTC, AleksandraZakharova commented on main.css
> +    cursor: url(./image/pointer.svg) 14.47 15.25, pointer;
fixed

2021-10-24 13:11 UTC, AleksandraZakharova commented on main.css
> +h1{
fixed

2021-10-24 13:11 UTC, AleksandraZakharova commented on main.css
> +
fixed

2021-10-24 13:14 UTC, AleksandraZakharova commented on index.html
> +                <footer class="footer">Footer</div>
done

2021-10-24 13:14 UTC, AleksandraZakharova commented on index.html
> +                        <div class="about section">
fixed

2021-10-24 13:15 UTC, AleksandraZakharova commented on index.html
> +                            </div>
done

2021-10-24 13:15 UTC, AleksandraZakharova commented on main.css
> +html,
fixed

2021-10-24 13:30 UTC, AleksandraZakharova commented on main.css
> +    font-family: 'Montserrat', sans-serif;
fixed

2021-10-24 13:31 UTC, AleksandraZakharova commented on main.css
> +    padding: 0;
fixed

2021-10-24 13:32 UTC, AleksandraZakharova commented on main.css
> +    font-style: normal;
fixed

2021-10-24 13:32 UTC, AleksandraZakharova commented on main.css
> +    margin: 0;
fixed

2021-10-24 13:59 UTC, AleksandraZakharova commented on index.html
> +                        <span class="time-table">с 10.00 до 19.00 без выходных</span>
fixed

2021-10-24 15:02 UTC, AleksandraZakharova commented on index.html
> +                                <div class="circle"></div>
fixed

2021-10-24 15:11 UTC, AleksandraZakharova commented on index.html
> +                                <div>
Разобралась с ошибкой, поэтому теперь он действительно не нужен)
Исправила

2021-10-24 15:43 UTC, AleksandraZakharova commented on index.html
> +                                    <img src="./image/vk.svg">
fixed

2021-10-24 15:56 UTC, AleksandraZakharova commented on main.css
> +    right: calc((100% - 1110px) / 2);
Если честно, то не знаю как) если я задам position:absolute для блока с соц сетями, то тогда при скролле страницы он не будет на одном и том же месте, а как задать отступы для fixed позиционирования без calc не знаю) помоги, пожалуйста

2021-11-16 05:12 UTC, studenttsu commented on main.css
> +    right: calc((100% - 1110px) / 2);
Вот пример, показывал прошлому потоку. Обрати внимание на взаимное расположение элементов в шапке

https://competent-mclean-4c8788.netlify.app/

2021-11-16 05:12 UTC, studenttsu approved these changes
Всё круто, работа принята)

2021-11-22 12:02 UTC, merged